=== primefaces/legacy/legacy/tags/0_9_1/src/main/resources-maven-jsf/misc/component.dtd
<!ELEMENT component (tag,tagClass,componentClass,componentType,componentFamily,rendererType?,rendererClass?,parent,attributes)>
<!ELEMENT tagman (#PCDATA)>
<!ELEMENT tagClass (#PCDATA)>
<!ELEMENT componentClass (#PCDATA)>
<!ELEMENT componentType (#PCDATA)>
<!ELEMENT componentFamily (#PCDATA)>
<!ELEMENT rendererType (#PCDATA)>
<!ELEMENT rendererClass (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (name,required,type,ignoreInComponent?,defaultValue?,description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT ignoreInComponent (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== primefaces/legacy/legacy/tags/1_0_0/src/main/resources-maven-jsf/ui/growl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>growl</tag>
	<tagClass>org.primefaces.component.growl.GrowlTag</tagClass>
	<componentClass>org.primefaces.component.growl.Growl</componentClass>
	<componentType>org.primefaces.component.Growl</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.GrowlRenderer</rendererType>
	<rendererClass>org.primefaces.component.growl.GrowlRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>sticky</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Specifies if the message should stay instead of hidden automatically.</description>
		</attribute>
		<attribute>
			<name>showSummary</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>Specifies if the summary of the FacesMessage should be displayed.</description>
		</attribute>
		<attribute>
			<name>showDetail</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Specifies if the detail of the FacesMessage should be displayed.</description>
		</attribute>
		<attribute>
			<name>globalOnly</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>When true, only facesmessages with no clientIds are displayed.</description>
		</attribute>
		<attribute>
			<name>life</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>6000</defaultValue>
			<description>Duration to display a non-sticky message.</description>
		</attribute>
		<attribute>
			<name>warnIcon</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Image for the warning messages.</description>
		</attribute>
		<attribute>
			<name>infoIcon</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Image for the info messages.</description>
		</attribute>
		<attribute>
			<name>errorIcon</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Image for the error messages.</description>
		</attribute>
		<attribute>
			<name>fatalIcon</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Image for the fatal messages.</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/jquery/plugins/gritter/assets/gritter.css</name>
		</resource>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/jquery/plugins/gritter/jquery.gritter.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_0_0/src/main/resources-maven-jsf/ui/menubar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY container_component_attributes			SYSTEM "../entities/container_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>menubar</tag>
	<tagClass>org.primefaces.component.menubar.MenubarTag</tagClass>
	<componentClass>org.primefaces.component.menubar.Menubar</componentClass>
	<componentType>org.primefaces.component.Menubar</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.MenubarRenderer</rendererType>
	<rendererClass>org.primefaces.component.menubar.MenubarRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>autoSubmenuDisplay</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>
				When set to true, submenus are displayed on mouseover of a menuitem.
			</description>
		</attribute>
		<attribute>
			<name>effect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>FADE</defaultValue>
			<description>
				Sets the effect for the menu display, default value is "FADE". Possible values are "FADE", "SLIDE", "NONE". Use "NONE" to disable animation at all.
			</description>
		</attribute>
		<attribute>
			<name>effectDuration</name>
			<required>false</required>
			<type>java.lang.Double</type>
			<defaultValue>0.25</defaultValue>
			<description>
				Sets the effect for the menu display
			</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/yui/menu/assets/skins/sam/menu.css</name>
		</resource>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/yui/container/container-min.js</name>
		</resource>
		<resource>
			<name>/yui/menu/menu-min.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_0_1/src/main/resources-maven-jsf/ui/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY container_component_attributes			SYSTEM "../entities/container_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>menu</tag>
	<tagClass>org.primefaces.component.menu.MenuTag</tagClass>
	<componentClass>org.primefaces.component.menu.Menu</componentClass>
	<componentType>org.primefaces.component.Menu</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.MenuRenderer</rendererType>
	<rendererClass>org.primefaces.component.menu.MenuRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>visible</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>
				Sets the menu's visibility, true by default
			</description>
		</attribute>
		<attribute>
			<name>x</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>-1</defaultValue>
			<description>Sets the element's "left" style property. Only applies to "dynamic" menus</description>
		</attribute>
		<attribute>
			<name>y</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>-1</defaultValue>
			<description>Sets the element's "top" style property. Only applies to "dynamic" menus.</description>
		</attribute>
		<attribute>
			<name>fixedCenter</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description> Boolean value that specifies whether the component
				should be automatically centered in the viewport on window scroll and resize. Only applies to "dynamic" menus.</description>
		</attribute>
		<attribute>
			<name>constraintToViewport</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>
				Boolean indicating if the Menu will try to remain inside the boundaries of the size of viewport. Only applies to "dynamic" menus.
			</description>
		</attribute>
		<attribute>
			<name>position</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>static</defaultValue>
			<description>
				Sets the way menu is placed on the page, when "static" menu is displayed in the normal flow, when set to "dynamic" menu is not on the normal flow
				allowing overlaying. Default value is "static".
			</description>
		</attribute>
		<attribute>
			<name>clickToHide</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>
				Sets the behavior when outside of the menu is clicked, default is false. Only applies to "dynamic" menus
			</description>
		</attribute>
		<attribute>
			<name>keepOpen</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>
				Sets the behavior when menu is clicked, default is true. Only applies to "dynamic" menus.
			</description>
		</attribute>
		<attribute>
			<name>tiered</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>
				Sets the tiered mode, when set to true menu will be rendered in different tiers, default is false. Only applies to "dynamic" menus.
			</description>
		</attribute>
		<attribute>
			<name>effect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>FADE</defaultValue>
			<description>
				Sets the effect for the menu display, default value is FADE. Possible values are "FADE", "SLIDE", "NONE". Use "NONE" to disable animation at all.
			</description>
		</attribute>
		<attribute>
			<name>effectDuration</name>
			<required>false</required>
			<type>java.lang.Double</type>
			<defaultValue>0.25</defaultValue>
			<description>
				Sets the effect for the menu display
			</description>
		</attribute>
		<attribute>
			<name>autoSubmenuDisplay</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>
				When set to true, submenus are displayed on mouseover of a menuitem.
			</description>
		</attribute>
		<attribute>
			<name>showDelay</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>250</defaultValue>
			<description>
				Sets the duration in milliseconds before a submenu is displayed. Only applies to "dynamic" menus.
			</description>
		</attribute>
		<attribute>
			<name>hideDelay</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>0</defaultValue>
			<description>
				Sets the duration in milliseconds before a menu is hidden Only applies to "dynamic" menus.
			</description>
		</attribute>
		<attribute>
			<name>submenuHideDelay</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>250</defaultValue>
			<description>
				Sets the duration in milliseconds before a submenu is hidden. Only applies to "dynamic" menus.
			</description>
		</attribute>
		<attribute>
			<name>context</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Arguments for context sensitive positioning.
			</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Style of the main container element.
			</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Style class of the main container element.
			</description>
		</attribute>
		<attribute>
			<name>zindex</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>java.lang.Integer.MAX_VALUE</defaultValue>
			<description>zindex property to control overlapping with other elements</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/yui/menu/assets/skins/sam/menu.css</name>
		</resource>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/yui/container/container-min.js</name>
		</resource>
		<resource>
			<name>/yui/menu/menu-min.js</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_0_1/src/main/resources-maven-jsf/ui/keyboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY html_input_text_attributes				SYSTEM "../entities/html_input_text_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>keyboard</tag>
	<tagClass>org.primefaces.component.keyboard.KeyboardTag</tagClass>
	<componentClass>org.primefaces.component.keyboard.Keyboard</componentClass>
	<componentType>org.primefaces.component.Keyboard</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.KeyboardRenderer</rendererType>
	<rendererClass>org.primefaces.component.keyboard.KeyboardRenderer</rendererClass>
	<parent>javax.faces.component.html.HtmlInputText</parent>
	<attributes>
		&input_component_attributes;
		&html_input_text_attributes;
		&widget_var_attribute;
		<attribute>
			<name>password</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Displays a password text when enabled.</description>
		</attribute>
		<attribute>
			<name>showMode</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>focus</defaultValue>
			<description>Specifies the display mode, 'focus','button','both'.</description>
		</attribute>
		<attribute>
			<name>buttonImage</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Image of the button trigger that displays the keyboard.</description>
		</attribute>
		<attribute>
			<name>buttonImageOnly</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>When set to true only image of the button is displayed.</description>
		</attribute>
		<attribute>
			<name>effect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>fadeIn</defaultValue>
			<description>Effect of the display animation.</description>
		</attribute>
		<attribute>
			<name>effectDuration</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Length of the display animation.</description>
		</attribute>
		<attribute>
			<name>layout</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>qwerty</defaultValue>
			<description>Layout the of the keyboard, can be 'qwerty','alphabetic' or custom.</description>
		</attribute>
		<attribute>
			<name>layoutTemplate</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Template of the custom layout.</description>
		</attribute>
		<attribute>
			<name>keypadOnly</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>When set to true, a keypad will be displayed instead of the whole keyboard.</description>
		</attribute>
		<attribute>
			<name>promptLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Label for the prompt text.</description>
		</attribute>
		<attribute>
			<name>closeLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Label for the close key.</description>
		</attribute>
		<attribute>
			<name>clearLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Label for the clear key.</description>
		</attribute>
		<attribute>
			<name>backspaceLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Label for the backspace key.</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/jquery/plugins/effects/effects.js</name>
		</resource>
		<resource>
			<name>/jquery/plugins/keyboard/keypad.css</name>
		</resource>
		<resource>
			<name>/jquery/plugins/keyboard/keypad.min.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
		<resource>
			<name>/primefaces/keyboard/keyboard.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_1/src/main/resources-maven-jsf/ui/resource.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY html_input_textarea_attributes			SYSTEM "../entities/html_input_textarea_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>resource</tag>
	<tagClass>org.primefaces.component.resource.ResourceTag</tagClass>
	<componentClass>org.primefaces.component.resource.Resource</componentClass>
	<componentType>org.primefaces.component.Resource</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.ResourceRenderer</rendererType>
	<rendererClass>org.primefaces.component.resource.ResourceRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_ui_component_attributes;
		<attribute>
			<name>name</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Path of the resource to be exluded.</description>
		</attribute>
	</attributes>
</component>

=== primefaces/legacy/legacy/tags/0_9_0/src/main/resources-maven-jsf/components/imageSwitcher.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>imageSwitcher</tag>
	<tagClass>org.primefaces.ui.component.imageswitcher.ImageSwitcherTag</tagClass>
	<componentClass>org.primefaces.ui.component.imageswitcher.ImageSwitcher</componentClass>
	<componentType>org.primefaces.ui.ImageSwitcher</componentType>
	<componentFamily>org.primefaces.ui</componentFamily>
	<rendererType>org.primefaces.ui.component.ImageSwitcherRenderer</rendererType>
	<rendererClass>org.primefaces.ui.component.imageswitcher.ImageSwitcherRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>effect</name>
			<required>true</required>
			<type>java.lang.String</type>
			<description>
				Effect to be used for switching
			</description>
		</attribute>
		<attribute>
			<name>speed</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<description>
				Transition speed in terms of milliseconds.
			</description>
			<defaultValue>500</defaultValue>
		</attribute>
		<attribute>
			<name>slideshowSpeed</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<description>
				Slideshow speed in terms of milliseconds
			</description>
			<defaultValue>3000</defaultValue>
		</attribute>
		<attribute>
			<name>slideshowAuto</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>Starts slideshow automatically</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/jquery/plugins/imageswitch/imageswitch.js</name>
		</resource>
		<resource>
			<name>/primefaces/imageswitcher/imageswitcher.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_1/src/main/resources-maven-jsf/ui/confirmDialog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>confirmDialog</tag>
	<tagClass>org.primefaces.component.confirmdialog.ConfirmDialogTag</tagClass>
	<componentClass>org.primefaces.component.confirmdialog.ConfirmDialog</componentClass>
	<componentType>org.primefaces.component.ConfirmDialog</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.ConfirmDialogRenderer</rendererType>
	<rendererClass>org.primefaces.component.confirmdialog.ConfirmDialogRenderer</rendererClass>
	<parent>javax.faces.component.UIPanel</parent>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>message</name>
			<required>true</required>
			<type>java.lang.String</type>
			<description>The text displayed in the dialog</description>
		</attribute>
		<attribute>
			<name>header</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>The text displayed in the dialog's header part</description>
		</attribute>
		<attribute>
			<name>severity</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>alert</defaultValue>
			<description>Icon for the severity of the message</description>
		</attribute>
		<attribute>
			<name>draggable</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>
				Boolean value whether to allow the user to drag the Panel using its header.
			</description>
		</attribute>
		<attribute>
			<name>modal</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>
				Boolean value that specifies whether the document should be
				shielded with a partially transparent mask to require the user
				to close the Panel before being able to activate any elements in
				the document.
			</description>
		</attribute>
		<attribute>
			<name>width</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>300</defaultValue>
			<description>Width of the element in pixels</description>
		</attribute>
		<attribute>
			<name>height</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>java.lang.Integer.MIN_VALUE</defaultValue>
			<description>Height of the element in pixels</description>
		</attribute>
		<attribute>
			<name>zindex</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>1000</defaultValue>
			<description>zindex property to control overlapping with other elements</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style class of the main container of dialog.</description>
		</attribute>
		<attribute>
			<name>showEffect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Effect to use when showing the dialog</description>
		</attribute>
		<attribute>
			<name>hideEffect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Effect to use when hiding the dialog</description>
		</attribute>
		<attribute>
			<name>position</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Defines where the dialog should be displayed</description>
		</attribute>
		<attribute>
			<name>closeOnEscape</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>Defines if dialog should be closed when escape key is pressed</description>
		</attribute>
		<attribute>
			<name>closable</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>Defines if close icon should be displayed or not</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/jquery/plugins/ui/jquery.ui.dialog.css</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/jquery/plugins/ui/jquery-ui.custom.js</name>
		</resource>	
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
		<resource>
			<name>/primefaces/confirmdialog/confirmdialog.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_0_2/src/main/resources-maven-jsf/ui/tabview.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>tabView</tag>
	<tagClass>org.primefaces.component.tabview.TabViewTag</tagClass>
	<componentClass>org.primefaces.component.tabview.TabView</componentClass>
	<componentType>org.primefaces.component.TabView</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.TabViewRenderer</rendererType>
	<rendererClass>org.primefaces.component.tabview.TabViewRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<ajaxComponent>true</ajaxComponent>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>activeIndex</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>0</defaultValue>
			<description>Index of the active tab</description>
		</attribute>
		<attribute>
			<name>orientation</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Defines how the tabs should oriented, valid values are top|bottom|left|right</description>
		</attribute>
		<attribute>
			<name>contentTransition</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Applies a transition effect during changing the tabs, default value is false</description>
		</attribute>
		<attribute>
			<name>dynamic</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Specifies the toggleMode, dynamic setting fetches it's content with ajax on tab switch.</description>
		</attribute>
		<attribute>
			<name>cache</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>When tab contents are lazy loaded by ajax toggleMode, caching only retrieves the tab contents once and subsequent toggles of a cached tab
			does not communicate with server. If caching is turned off, tab contents are refetched from server each time tab is clicked. This setting is true by default.</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/yui/tabview/assets/skins/sam/tabview.css</name>
		</resource>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/yui/tabview/tabview-min.js</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
		<resource>
			<name>/primefaces/tabview/tabview.js</name>
		</resource>
	</resources>
</component>
