=== primefaces/legacy/legacy/tags/0_9_1/src/main/resources-maven-jsf/misc/component.dtd
<!ELEMENT component (tag,tagClass,componentClass,componentType,componentFamily,rendererType?,rendererClass?,parent,attributes)>
<!ELEMENT tagman (#PCDATA)>
<!ELEMENT tagClass (#PCDATA)>
<!ELEMENT componentClass (#PCDATA)>
<!ELEMENT componentType (#PCDATA)>
<!ELEMENT componentFamily (#PCDATA)>
<!ELEMENT rendererType (#PCDATA)>
<!ELEMENT rendererClass (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (name,required,type,ignoreInComponent?,defaultValue?,description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT ignoreInComponent (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== primefaces/legacy/legacy/tags/1_0_2/src/main/resources-maven-jsf/ui/breadCrumb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY container_component_attributes			SYSTEM "../entities/container_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>breadCrumb</tag>
	<tagClass>org.primefaces.component.breadcrumb.BreadCrumbTag</tagClass>
	<componentClass>org.primefaces.component.breadcrumb.BreadCrumb</componentClass>
	<componentType>org.primefaces.component.BreadCrumb</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.BreadCrumbRenderer</rendererType>
	<rendererClass>org.primefaces.component.breadcrumb.BreadCrumbRenderer</rendererClass>
	<parent>org.primefaces.component.menu.AbstractMenu</parent>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>model</name>
			<required>false</required>
			<type>org.primefaces.model.MenuModel</type>
			<description>
				An org.primefaces.model.MenuModel instance to build menu dynamically.
			</description>
		</attribute>
		<attribute>
			<name>expandedEndItems</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>1</defaultValue>
			<description>Number of expanded menuitems at end.</description>
		</attribute>
		<attribute>
			<name>expandedBeginningItems</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>1</defaultValue>
			<description>Number of expanded menuitems at beginning.</description>
		</attribute>
		<attribute>
			<name>expandEffectDuration</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>800</defaultValue>
			<description>Expand effect duration in milliseconds.</description>
		</attribute>
		<attribute>
			<name>collapseEffectDuration</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>500</defaultValue>
			<description>Collapse effect duration in milliseconds.</description>
		</attribute>
		<attribute>
			<name>initialCollapseEffectDuration</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>600</defaultValue>
			<description>Initial collapse effect duration in milliseconds.</description>
		</attribute>
		<attribute>
			<name>previewWidth</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>5</defaultValue>
			<description>Preview width of a collapsed menuitem.</description>
		</attribute>
		<attribute>
			<name>preview</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Specifies preview mode, when set to false menuitems will not collapse.</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style of the main container element.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style class of the main container element.</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/jquery/plugins/breadcrumb/breadcrumb.css</name>
		</resource>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
		<resource>
			<name>/jquery/plugins/breadcrumb/jBreadCrumb.1.1.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_0_1/src/main/resources-maven-jsf/ui/dataTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY data_component_attributes				SYSTEM "../entities/data_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>dataTable</tag>
	<tagClass>org.primefaces.component.datatable.DataTableTag</tagClass>
	<componentClass>org.primefaces.component.datatable.DataTable</componentClass>
	<componentType>org.primefaces.component.DataTable</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.DataTableRenderer</rendererType>
	<rendererClass>org.primefaces.component.datatable.DataTableRenderer</rendererClass>
	<parent>javax.faces.component.UIData</parent>
	<ajaxComponent>true</ajaxComponent>
	<attributes>
		&data_component_attributes;
		&widget_var_attribute;
		<attribute>
			<name>paginator</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Enables paginator, default value is false</description>
		</attribute>
		<attribute>
			<name>paginatorTemplate</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Template for the paginator layout, default value is "{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"</description>
		</attribute>
		<attribute>
			<name>rowsPerPageTemplate</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Template for the rowsPerPage dropdown, default value is "25,50,100"</description>
		</attribute>
		<attribute>
			<name>scrollable</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Controls scrolling, default value is false</description>
		</attribute>
		<attribute>
			<name>width</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Width of a scrollable datatable
			</description>
		</attribute>
		<attribute>
			<name>height</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Height of a scrollable datatable
			</description>
		</attribute>
		<attribute>
			<name>firstPageLinkLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Label of the first link paginator
			</description>
		</attribute>
		<attribute>
			<name>previousPageLinkLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Label of the previous link paginator
			</description>
		</attribute>
		<attribute>
			<name>nextPageLinkLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Label of the next link paginator
			</description>
		</attribute>
		<attribute>
			<name>lastPageLinkLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Label of the last link paginator
			</description>
		</attribute>
		<attribute>
			<name>selectionMode</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Type for row click selection, can be 'multiple' or 'single'.
			</description>
		</attribute>
		<attribute>
			<name>selection</name>
			<required>false</required>
			<type>java.lang.Object</type>
			<description>
				An object array that'll be used to assign the selected data.
			</description>
		</attribute>
		<attribute>
			<name>dynamic</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>
				When set to true sorting and paging will be done on server via ajax, default is false meaning sorting-paging is done on client side.
			</description>
		</attribute>
		<attribute>
			<name>lazy</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>
				Controls lazy loading.
			</description>
		</attribute>
		<attribute>
			<name>rowIndexVar</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Variable name referring to the rowIndex being processed.
			</description>
		</attribute>
		<attribute>
			<name>paginatorPosition</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>both</defaultValue>
			<description>
				Position of the paginator, valid values are "both","top","bottom".
			</description>
		</attribute>
		<attribute>
			<name>emptyMessage</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Message to be shown when there're no records to display.
			</description>
		</attribute>
		<attribute>
			<name>errorMessage</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Message to be shown when there's an error loading the data.
			</description>
		</attribute>
		<attribute>
			<name>loadingMessage</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Message to be shown when loading the data with ajax.
			</description>
		</attribute>
		<attribute>
			<name>sortAscMessage</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Message to be shown to sort a column data in ascending order.
			</description>
		</attribute>
		<attribute>
			<name>sortDescMessage</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Message to be shown to sort a column data in descending order.
			</description>
		</attribute>
		<attribute>
			<name>update</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Client side id of the component(s) to be updated after ajax row selection.
			</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style of the main container element of table.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>StyleClass of the main container element of table.</description>
		</attribute>
		<attribute>
			<name>onselectStart</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Javascript event handler to be called before ajax request for instant ajax row selection request begins.
			</description>
		</attribute>
		<attribute>
			<name>onselectComplete</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Javascript event handler to be called after ajax request for instant ajax row selection request is completed.
			</description>
		</attribute>
		<attribute>
			<name>dblClickSelect</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>
				By default single click triggers row selection feature, setting dblClickSelect enabled double click requirement for row selection.
			</description>
		</attribute>
		<attribute>
			<name>page</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>1</defaultValue>
			<description>Index of the current page, first page is 1.</description>
		</attribute>
		<attribute>
			<name>pageLinks</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>10</defaultValue>
			<description>Number of pageLinks to display when paginator is enabled, defaults to 10.</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/yui/paginator/assets/skins/sam/paginator.css</name>
		</resource>
		<resource>
			<name>/yui/datatable/assets/skins/sam/datatable.css</name>
		</resource>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/yui/json/json-min.js</name>
		</resource>
		<resource>
			<name>/yui/datasource/datasource-min.js</name>
		</resource>
		<resource>
			<name>/yui/paginator/paginator-min.js</name>
		</resource>
		<resource>
			<name>/yui/datatable/datatable-min.js</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
		<resource>
			<name>/primefaces/datatable/datatable.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/0_8_3/src/main/resources-maven-jsf/components/lineChart.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		/* * Licensed to the Apache Software Foundation (ASF) under one * or
		more contributor license agreements. See the NOTICE file * distributed
		with this work for additional information * regarding copyright
		ownership. The ASF licenses this file * to you under the Apache
		License, Version 2.0 (the * "License"); you may not use this file
		except in compliance * with the License. You may obtain a copy of the
		License at * * http://www.apache.org/licenses/LICENSE-2.0 * * Unless
		required by applicable law or agreed to in writing, * software
		distributed under the License is distributed on an * "AS IS" BASIS,
		WITHOUT WARRANTIES OR CONDITIONS OF ANY * KIND, either express or
		implied. See the License for the * specific language governing
		permissions and limitations * under the License. */ //
	-->

<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>lineChart</tag>
	<tagClass>org.primefaces.ui.component.chart.line.LineChartTag</tagClass>
	<componentClass>org.primefaces.ui.component.chart.line.LineChart</componentClass>
	<componentType>org.primefaces.ui.LineChart</componentType>
	<componentFamily>org.primefaces</componentFamily>
	<rendererType>org.primefaces.ui.component.chart.LineChartRenderer</rendererType>
	<rendererClass>org.primefaces.ui.component.chart.line.LineChartRenderer</rendererClass>
	<parent>org.primefaces.ui.component.chart.UIChart</parent>
	<ajaxComponent>true</ajaxComponent>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>widgetVar</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Javascript variable name of the wrapped yui widget 
			</description>
		</attribute>
		<attribute>
			<name>value</name>
			<required>true</required>
			<type>java.lang.Object</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>Data to be displayed on the chart</description>
		</attribute>
		<attribute>
			<name>var</name>
			<required>true</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<literal>true</literal>
			<description>Name of the data iterator</description>
		</attribute>
		<attribute>
			<name>xfield</name>
			<required>false</required>
			<type>java.lang.Object</type>
			<description>Field for the x axis</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>Style to apply to chart container element.</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>Javascript object that represents the chart style</description>
		</attribute>
		<attribute>
			<name>wmode</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				wmode property of the flash object.
			</description>
		</attribute>
		<attribute>
			<name>live</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<ignoreInComponent>true</ignoreInComponent>
			<description>When a chart is live, the data is refreshed based on the refreshInterval</description>
		</attribute>
		<attribute>
			<name>oncomplete</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Javascript event to be called when ajax request for item select event is completed.
			</description>
		</attribute>
		<attribute>
			<name>refreshInterval</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>3000</defaultValue>
			<ignoreInComponent>true</ignoreInComponent>
			<description>Refresh period of a live chart data in milliseconds</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/yui/datasource/datasource-min.js</name>
		</resource>
		<resource>
			<name>/yui/json/json-min.js</name>
		</resource>
		<resource>
			<name>/yui/cookie/cookie-min.js</name>
		</resource>
		<resource>
			<name>/yui/charts/charts-min.js</name>
		</resource>
		<resource>
			<name>/primefaces/ajax/ajax.js</name>
		</resource>
		<resource>
			<name>/yuiext/charts/charts.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_0_0/src/main/resources-maven-jsf/ui/wizard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>wizard</tag>
	<tagClass>org.primefaces.component.wizard.WizardTag</tagClass>
	<componentClass>org.primefaces.component.wizard.Wizard</componentClass>
	<componentType>org.primefaces.component.Wizard</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.WizardRenderer</rendererType>
	<rendererClass>org.primefaces.component.wizard.WizardRenderer</rendererClass>
	<parent>org.primefaces.component.wizard.UIWizard</parent>
	<ajaxComponent>true</ajaxComponent>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>step</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>0</defaultValue>
			<description>Index of the current step in flow</description>
		</attribute>
		<attribute>
			<name>effect</name>
			<required>true</required>
			<type>java.lang.String</type>
			<defaultValue>slide</defaultValue>
			<description>
				Effect to be used for switching, "slide" or "toggle".
			</description>
		</attribute>
		<attribute>
			<name>width</name>
			<required>true</required>
			<type>java.lang.Integer</type>
			<defaultValue>400</defaultValue>
			<description>
				Width of the viewport in pixels
			</description>
		</attribute>
		<attribute>
			<name>height</name>
			<required>true</required>
			<type>java.lang.Integer</type>
			<defaultValue>400</defaultValue>
			<description>
				Height of the viewport in pixels
			</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style of the main wizard container</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>StyleClass of the main wizard container</description>
		</attribute>
		<attribute>
			<name>speed</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>500</defaultValue>
			<description>Speed of animation in ms.</description>
		</attribute>
		<attribute>
			<name>customUI</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>When customUI is turned on, navigational controls won't be rendered and page authors can create their own ui using client side api.</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/primefaces/wizard/assets/wizard.css</name>
		</resource>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/jquery/plugins/tabswitch/tabswitch.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
		<resource>
			<name>/primefaces/wizard/wizard.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/0_9_2/src/main/resources-maven-jsf/components/layoutUnit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>layoutUnit</tag>
	<tagClass>org.primefaces.ui.component.layout.LayoutUnitTag</tagClass>
	<componentClass>org.primefaces.ui.component.layout.LayoutUnit</componentClass>
	<componentType>org.primefaces.ui.LayoutUnit</componentType>
	<componentFamily>org.primefaces.ui</componentFamily>
	<rendererType>org.primefaces.ui.component.LayoutUnitRenderer</rendererType>
	<rendererClass>org.primefaces.ui.component.layout.LayoutUnitRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>position</name>
			<required>true</required>
			<type>java.lang.String</type>
			<description>Position of the unit, can be "top","bottom","center","left","right"</description>
		</attribute>
		<attribute>
			<name>header</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Header text of the unit</description>
		</attribute>
		<attribute>
			<name>footer</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Footer text of the unit</description>
		</attribute>
		<attribute>
			<name>width</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Width of the unit in pixels, applies to left and right units</description>
		</attribute>
		<attribute>
			<name>height</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Height of the unit in pixels, applies to top and bottom units</description>
		</attribute>
		<attribute>
			<name>resize</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Makes the unit resizable.</description>
		</attribute>
		<attribute>
			<name>gutter</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Specifies the gutter size which is applied before the content.</description>
		</attribute>
		<attribute>
			<name>collapse</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Makes the unit collapsable.</description>
		</attribute>
		<attribute>
			<name>scroll</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>Makes the unit scrollable when content is bigger than the unit.</description>
		</attribute>
		<attribute>
			<name>animate</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Animates unit when expanding and collapsing.</description>
		</attribute>
	</attributes>
</component>

=== primefaces/legacy/legacy/tags/0_8_0/src/main/resources-maven-jsf/components/pieChart.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		/* * Licensed to the Apache Software Foundation (ASF) under one * or
		more contributor license agreements. See the NOTICE file * distributed
		with this work for additional information * regarding copyright
		ownership. The ASF licenses this file * to you under the Apache
		License, Version 2.0 (the * "License"); you may not use this file
		except in compliance * with the License. You may obtain a copy of the
		License at * * http://www.apache.org/licenses/LICENSE-2.0 * * Unless
		required by applicable law or agreed to in writing, * software
		distributed under the License is distributed on an * "AS IS" BASIS,
		WITHOUT WARRANTIES OR CONDITIONS OF ANY * KIND, either express or
		implied. See the License for the * specific language governing
		permissions and limitations * under the License. */ //
	-->

<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>pieChart</tag>
	<tagClass>org.primefaces.ui.component.chart.pie.PieChartTag</tagClass>
	<componentClass>org.primefaces.ui.component.chart.pie.PieChart</componentClass>
	<componentType>org.primefaces.ui.chart.PieChart</componentType>
	<componentFamily>org.primefaces</componentFamily>
	<rendererType>org.primefaces.ui.component.chart.PieChartRenderer</rendererType>
	<rendererClass>org.primefaces.ui.component.chart.pie.PieChartRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>value</name>
			<required>true</required>
			<type>java.lang.Object</type>
			<description>Data to be displayed on the chart</description>
		</attribute>
		<attribute>
			<name>var</name>
			<required>true</required>
			<type>java.lang.String</type>
			<description>Name of the data iterator</description>
		</attribute>
		<attribute>
			<name>categoryField</name>
			<required>false</required>
			<type>java.lang.Object</type>
			<description>Pie category field</description>
		</attribute>
		<attribute>
			<name>dataField</name>
			<required>false</required>
			<type>java.lang.Object</type>
			<description>Pie category date field</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style class to apply to chart container element.</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Javascript object that represents the chart style</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/yui/datasource/datasource-min.js</name>
		</resource>
		<resource>
			<name>/yui/json/json-min.js</name>
		</resource>
		<resource>
			<name>/yui/charts/charts-experimental-min.js</name>
		</resource>
	</resources>
</component>
