=== primefaces/legacy/legacy/tags/0_9_1/src/main/resources-maven-jsf/misc/component.dtd
<!ELEMENT component (tag,tagClass,componentClass,componentType,componentFamily,rendererType?,rendererClass?,parent,attributes)>
<!ELEMENT tagman (#PCDATA)>
<!ELEMENT tagClass (#PCDATA)>
<!ELEMENT componentClass (#PCDATA)>
<!ELEMENT componentType (#PCDATA)>
<!ELEMENT componentFamily (#PCDATA)>
<!ELEMENT rendererType (#PCDATA)>
<!ELEMENT rendererClass (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (name,required,type,ignoreInComponent?,defaultValue?,description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT ignoreInComponent (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== primefaces/legacy/legacy/tags/1_0_0_RC/src/main/resources-maven-jsf/ui/column.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>column</tag>
	<tagClass>org.primefaces.component.column.ColumnTag</tagClass>
	<componentClass>org.primefaces.component.column.Column</componentClass>
	<componentType>org.primefaces.component.Column</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<parent>javax.faces.component.UIColumn</parent>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>sortBy</name>
			<required>false</required>
			<type>java.lang.Object</type>
			<description>Property to be used when sorting this column either on client side or server side with ajax.</description>
		</attribute>
		<attribute>
			<name>resizable</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Boolean to make the column width resizable, default is false</description>
		</attribute>
		<attribute>
			<name>filter</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>When set to true, places a data filter to the column header</description>
		</attribute>
		<attribute>
			<name>selectionMode</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Type of the selection column; 'multiple' or 'single'. Multiple places checkboxes and Single places radio buttons inside this column.
			</description>
		</attribute>
		<attribute>
			<name>parser</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Type of parser used to identify the type of data presented in the column.
			</description>
		</attribute>
		<attribute>
			<name>width</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>java.lang.Integer.MIN_VALUE</defaultValue>
			<description>
				Width of column in pixelsm.
			</description>
		</attribute>
	</attributes>
</component>

=== primefaces/legacy/legacy/trunk/src/main/resources-maven-jsf/ui/wizard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>wizard</tag>
	<tagClass>org.primefaces.component.wizard.WizardTag</tagClass>
	<componentClass>org.primefaces.component.wizard.Wizard</componentClass>
	<componentHandlerClass>org.primefaces.component.wizard.WizardHandler</componentHandlerClass>
	<componentType>org.primefaces.component.Wizard</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.WizardRenderer</rendererType>
	<rendererClass>org.primefaces.component.wizard.WizardRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<interfaces>
		<interface>
			<name>org.primefaces.component.api.AjaxComponent</name>
		</interface>
		<interface>
			<name>javax.faces.component.NamingContainer</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>step</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Id of the current step in flow</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style of the main wizard container</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>StyleClass of the main wizard container</description>
		</attribute>
		<attribute>
			<name>flowListener</name>
			<required>false</required>
			<type>javax.el.MethodExpression</type>
			<method-signature>void flowListener()</method-signature>
			<description>A server side listener to be invoked when wizard flow is processed back or forth</description>
		</attribute>
		<attribute>
			<name>showNavBar</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>Specifies visibility of default navigation controls in navigation bar.</description>
		</attribute>
		<attribute>
			<name>onback</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Javascript event handler to be invoked when flow goes back.</description>
		</attribute>
		<attribute>
			<name>onnext</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Javascript event handler to be invoked when flow goes next.</description>
		</attribute>
		<attribute>
			<name>nextLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Next</defaultValue>
			<description>Label of the next step navigation button.</description>
		</attribute>
		<attribute>
			<name>backLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Back</defaultValue>
			<description>Label of the back step navigation button.</description>
		</attribute>
		<attribute>
			<name>effect</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>Enabled fade effect during pagination.</description>
		</attribute>
		<attribute>
			<name>effectSpeed</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>normal</defaultValue>
			<description>Speed of the fade effect during pagination.</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/primefaces/wizard/wizard.css</name>
		</resource>
		<resource>
			<name>/jquery/plugins/ui/jquery.ui.button.css</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/jquery/plugins/ui/jquery-ui.custom.js</name>
		</resource>	
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
		<resource>
			<name>/primefaces/wizard/wizard.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_1/src/main/resources-maven-jsf/ui/treeTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY data_component_attributes				SYSTEM "../entities/data_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>treeTable</tag>
	<tagClass>org.primefaces.component.treetable.TreeTableTag</tagClass>
	<componentClass>org.primefaces.component.treetable.TreeTable</componentClass>
	<componentType>org.primefaces.component.TreeTable</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.TreeTableRenderer</rendererType>
	<rendererClass>org.primefaces.component.treetable.TreeTableRenderer</rendererClass>
	<parent>javax.faces.component.UIData</parent>
	<attributes>
		&data_component_attributes;
		&widget_var_attribute;
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style of the main container of panel.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style class of the main container of panel.</description>
		</attribute>
		<attribute>
			<name>readOnly</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>When readOnly, treeTable is rendered as expanded and expand/collapse is disabled</description>
		</attribute>
		<attribute>
			<name>expanded</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Rendered treeTable as expanded by defaul</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/primefaces/treetable/style/treetable.css</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
		<resource>
			<name>/primefaces/treetable/treetable.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_0_0_RC/src/main/resources-maven-jsf/ui/commandLink.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY command_component_attributes			SYSTEM "../entities/command_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
<!ENTITY html_command_button_attributes			SYSTEM "../entities/html_command_button_attributes.xml">
]>
<component>
	<tag>commandLink</tag>
	<tagClass>org.primefaces.component.commandlink.CommandLinkTag</tagClass>
	<componentClass>org.primefaces.component.commandlink.CommandLink</componentClass>
	<componentType>org.primefaces.component.CommandLink</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.CommandLinkRenderer</rendererType>
	<rendererClass>org.primefaces.component.commandlink.CommandLinkRenderer</rendererClass>
	<parent>javax.faces.component.html.HtmlCommandLink</parent>
	<attributes>
		&command_component_attributes;
		<attribute>
			<name>update</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Client side id of the component(s) to be updated after async partial submit request.
			</description>
		</attribute>
		<attribute>
			<name>onstart</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Javascript event to be called before ajax request begins.
			</description>
		</attribute>
		<attribute>
			<name>oncomplete</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Javascript event to be called when ajax request is completed.
			</description>
		</attribute>
		<attribute>
			<name>accesskey</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html accesskey attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>charset</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html chartset attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>coords</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html coords attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>dir</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Direction of the text displayed
			</description>
		</attribute>
		<attribute>
			<name>disabled</name>
			<required>false</required>
			<defaultValue>false</defaultValue>
			<type>java.lang.Boolean</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Flag to disable the link.
			</description>
		</attribute>
		<attribute>
			<name>hreflang</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html hreflang attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>rel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html rel attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>rev</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html rev attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>shape</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html shape attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>tabindex</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html tabindex attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>target</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html target attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>title</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html title attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>type</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Html type attribute for anchor.
			</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Style to apply to the anchor element.
			</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				Style class to apply to the anchor element.
			</description>
		</attribute>
		<attribute>
			<name>onblur</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onblur dom event handler
			</description>
		</attribute>
		<attribute>
			<name>onclick</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onclick dom event handler
			</description>
		</attribute>
		<attribute>
			<name>ondblclick</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 ondblclick dom event handler
			</description>
		</attribute>
		<attribute>
			<name>onfocus</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onfocus dom event handler
			</description>
		</attribute>
		<attribute>
			<name>onkeydown</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onkeydown dom event handler
			</description>
		</attribute>
		<attribute>
			<name>onkeypress</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onkeypress dom event handler
			</description>
		</attribute>
		<attribute>
			<name>onkeyup</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onkeyup dom event handler
			</description>
		</attribute>
		<attribute>
			<name>onmousedown</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onmousedown dom event handler
			</description>
		</attribute>
		<attribute>
			<name>onmousemove</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onmousemove dom event handler
			</description>
		</attribute>
		<attribute>
			<name>onmouseout</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onmouseout dom event handler
			</description>
		</attribute>
		<attribute>
			<name>onmouseover</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onmouseover dom event handler
			</description>
		</attribute>
		<attribute>
			<name>onmouseup</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
			<description>
				 onmouseup dom event handler
			</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/primefaces/ajax/ajax.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_0_0/src/main/resources-maven-jsf/ui/hotkey.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
]>
<component>
	<tag>hotkey</tag>
	<tagClass>org.primefaces.component.hotkey.HotkeyTag</tagClass>
	<componentClass>org.primefaces.component.hotkey.Hotkey</componentClass>
	<componentType>org.primefaces.component.Hotkey</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.HotkeyRenderer</rendererType>
	<rendererClass>org.primefaces.component.hotkey.HotkeyRenderer</rendererClass>
	<parent>javax.faces.component.UICommand</parent>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>actionListener</name>
			<required>false</required>
			<type>javax.faces.event.ActionListener</type>
			<method-signature>void actionListener(javax.faces.event.ActionEvent)</method-signature>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>action</name>
			<required>false</required>
			<type>javax.el.MethodExpression</type>
			<method-signature>java.lang.Object action()</method-signature>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>immediate</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>bind</name>
			<required>true</required>
			<type>java.lang.String</type>
			<description>The key binding.</description>
		</attribute>
		<attribute>
			<name>update</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Client side id of the component(s) to be updated after async partial submit request.
			</description>
		</attribute>
		<attribute>
			<name>process</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Comma seperated list of clientIds that will be processed partially in JSF lifecycle instead of the whole component tree.
			</description>
		</attribute>
		<attribute>
			<name>handler</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>The javascript event which will be performed when there is a event with the specific </description>
		</attribute>
		<attribute>
			<name>onstart</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Javascript event handler to be called before ajax request begins.
			</description>
		</attribute>
		<attribute>
			<name>oncomplete</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Javascript event handler to be called when ajax request is completed.
			</description>
		</attribute>
		<attribute>
			<name>onerror</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Javascript event handler to be called when ajax request fails.
			</description>
		</attribute>
		<attribute>
			<name>onsuccess</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Javascript event handler to be called when ajax request succeeds.
			</description>
		</attribute>
		<attribute>
			<name>global</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>
				Global ajax requests are listened by ajaxStatus component, setting global to false will not trigger ajaxStatus.
			</description>
		</attribute>
		<attribute>
			<name>async</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>
				When set to true, ajax requests will not be queued.
			</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/jquery/plugins/hotkey/jquery.hotkeys-0.7.9.min.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_1/src/main/resources-maven-jsf/ui/spreadsheet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>spreadsheet</tag>
	<tagClass>org.primefaces.component.spreadsheet.SpreadsheetTag</tagClass>
	<componentClass>org.primefaces.component.spreadsheet.Spreadsheet</componentClass>
	<componentType>org.primefaces.component.Spreadsheet</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.SpreadsheetRenderer</rendererType>
	<rendererClass>org.primefaces.component.spreadsheet.SpreadsheetRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>title</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Title text of the spreadsheet</description>
		</attribute>
		<attribute>
			<name>editable</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>Defines if display is editable or readonly</description>
		</attribute>
		<attribute>
			<name>columnWidth</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>java.lang.Integer.MIN_VALUE</defaultValue>
			<description>Global setting to define common width for each column in pixels</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/primefaces/sheet/jquery.sheet.css</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/jquery/plugins/ui/jquery-ui.custom.js</name>
		</resource>
		<resource>
			<name>/primefaces/sheet/jquery.sheet.js</name>
		</resource>
		<resource>
			<name>/primefaces/core/core.js</name>
		</resource>
		<resource>
			<name>/primefaces/sheet/sheet.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/tags/1_0_0_RC/src/main/resources-maven-jsf/ui/ajax.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>ajax</tag>
	<tagClass>org.primefaces.component.uiajax.UIAjaxTag</tagClass>
	<componentClass>org.primefaces.component.uiajax.UIAjax</componentClass>
	<componentType>org.primefaces.component.UIAjax</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.UIAjaxRenderer</rendererType>
	<rendererClass>org.primefaces.component.uiajax.UIAjaxRenderer</rendererClass>
	<parent>javax.faces.component.UICommand</parent>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>event</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Javascript event to trigger the ajax request.</description>
		</attribute>
		<attribute>
			<name>update</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Client side id of the component(s) to be updated after async partial submit request.
			</description>
		</attribute>
		<attribute>
			<name>actionListener</name>
			<required>false</required>
			<type>javax.faces.event.ActionListener</type>
			<method-signature>void actionListener(javax.faces.event.ActionEvent)</method-signature>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>action</name>
			<required>false</required>
			<type>javax.el.MethodExpression</type>
			<method-signature>java.lang.Object action()</method-signature>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>immediate</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>partialSubmit</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Flag for partial process, when set to true, parent form will be submitted but only the component the ajax event is attached to will be processed by JSF.</description>
		</attribute>
		<attribute>
			<name>onstart</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Javascript event to be called before ajax request begins.
			</description>
		</attribute>
		<attribute>
			<name>oncomplete</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Javascript event to be called when ajax request is completed.
			</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>/yui/utilities/utilities.js</name>
		</resource>
		<resource>
			<name>/jquery/jquery.js</name>
		</resource>
		<resource>
			<name>/primefaces/ajax/ajax.js</name>
		</resource>
	</resources>
</component>

=== primefaces/legacy/legacy/trunk/src/main/resources-maven-jsf/ui/chartSeries.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
]>
<component>
	<tag>chartSeries</tag>
	<tagClass>org.primefaces.component.chart.series.ChartSeriesTag</tagClass>
	<componentClass>org.primefaces.component.chart.series.ChartSeries</componentClass>
	<componentType>org.primefaces.component.chart.ChartSeries</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<parent>javax.faces.component.UIOutput</parent>
	<attributes>
		&standard_uicomponent_attributes;
		&output_component_attributes;
		<attribute>
			<name>label</name>
			<required>true</required>
			<type>java.lang.String</type>
			<description>Name of series</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Javascript object that represents the series style</description>
		</attribute>
	</attributes>
</component>
